## Numpy

In [2]:
import numpy as np

### Create Arrays

#### Create 1D Array

In [8]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [12]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row, 5 columns

array([[1, 2, 3, 4, 5]])

In [13]:
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

#### 2D Array

In [14]:
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


#### Arrays with in built functions

In [15]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [16]:
np.arange(0, 10, 2).reshape(5,1) # 5 rows 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
# identity matrix
np.eye(3) # diagonal 1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr = np.array([[1,2,3], [4,5,6]])

print("Array:\n", arr)
print("\nShape:", arr.shape)
print("\nNumber of dimensions:", arr.ndim)
print("\nSize (number of elements):", arr.size)
print("\nData type:", arr.dtype)
print("\nItem size (in bytes):", arr.itemsize) 

Array:
 [[1 2 3]
 [4 5 6]]

Shape: (2, 3)

Number of dimensions: 2

Size (number of elements): 6

Data type: int64

Item size (in bytes): 8


#### Numpy Vectorized Operation

In [30]:
arr1 = np.arange(1,6,1)
arr2 = np.arange(10,60,10)

##### Element wise addition

In [31]:
print("Addition:", arr1+arr2)

Addition: [11 22 33 44 55]


##### Element wise substraction

In [33]:
print("Substraction:", arr2 - arr1)

Substraction: [ 9 18 27 36 45]


#### Univeral Function

In [36]:
arr = np.arange(2,7,1)

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sinw
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### Array Slicing and Indexing

In [37]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array: \n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
print(arr[0][0])

1


In [55]:
print(arr[1:,2:])

[[ 7  8]
 [11 12]]


In [62]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


#### Modify Array Elements

In [63]:
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [65]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


#### Statistical Concepts -- Normalization

In [67]:
# to have mean of 0 and standard deviation of 1

data = np.arange(0,6,1)

# mean
mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean)/ std_dev

print("Normalized Data:", normalized_data)

Normalized Data: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


#### Logical Operations

In [75]:
data = np.arange(1,11,1)

data[(data >5) & (data < 8)]

array([6, 7])